version: '3'

services:
  websocket:
    container_name: websocket
    build: .
    ports:
      - "3333:3333"
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - ./tsconfig.json:/app/tsconfig.json
    command: yarn run dev